meta:
  engine: 4.0.2
  version: 1.0
  author: Mitchell J & Sam K
  git_repo: mitchell-johnstone/tabula
units:
  off: 2
points:
  zones:
    matrix:
      anchor:
        rotate: 5
      columns:
        pinky:
        ring.key.splay: -5
        ring.key.stagger: 12
        middle.key.stagger: 5
        index.key.stagger: -6
        inner.key.stagger: -2
      rows:
        bottom:
        home:
        top:
        numerals:
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -19]
      columns:
        near:
        home.key:
          splay: -15
          origin: [-11.75, -9]
        far.key:
          splay: -15
          origin: [-9.5, -9]
      rows:
        thumb:
  rotate: 
  mirror: &mirror
    ref: matrix_pinky_home
    distance: 255

outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      size: [cx+2, cy+2]
      corner: 2
  thumbfan_join:
    - what: polygon
      points:
        - ref: thumbfan_near_thumb
          shift: [-0.5 cx - 0.5 off, -0.5 cy - 0.5 off]
        - ref: thumbfan_home_thumb
          shift: [-0.5 cx, -0.5 cy - 0.5 off]
        - ref: thumbfan_far_thumb
          shift: [-0.5 cx, -0.5 cy - 0.5 off]
        - ref: thumbfan_far_thumb
          shift: [0.5 cx + 0.5 off, -0.5 cy - 0.5 off]
        - ref: thumbfan_far_thumb
          shift: [0.5 cx + 0.5 off, 0.5 cy + 0.5 off]
        - ref: thumbfan_far_thumb
          shift: [-0.5 cx, 0.5 cy + 0.5 off]
        - ref: thumbfan_home_thumb
          shift: [-0.5 cx, 0.5 cy + 0.5 off]
        - ref: thumbfan_near_thumb
          shift: [-0.5 cx - 0.5 off, 0.5 cy + 0.5 off]
  switches:
    - what: rectangle
      where: true
      asym: source
      size: 14
  keycaps:
    - what: rectangle 
      where: true
      asym: source
      size: [cx, cy] 
      corner: 1

cases:
  left:
    - what: outline
      name: matrix
#pcbs: <pcb config...> #optional
