meta:
  engine: 4.0.2
  version: 1.0
  author: Mitchell J & Sam K
  git_repo: mitchell-johnstone/tabula
units:
  off: 1 #1mm offset for casing
  up:    0.5cy + off
  down: -0.5cy - off
  left: -0.5cx - off
  right: 0.5cx + off
  # tl: [-0.5 cx - off,  0.5 cy + off]
  # bl: [-0.5 cx - off, -0.5 cy - off]
  # tr: [ 0.5 cx + off,  0.5 cy + off]
  # br: [ 0.5 cx + off, -0.5 cy - off]
points:
  zones:
    matrix:
      anchor:
        rotate: 10
      rows:
        bottom.row_net: P0
        home.row_net: P1
        top.row_net: P2
        nums.row_net: P3
      columns:
        outer:
          col_net: P4
        pinky:
          col_net: P5
          key.splay: -5
        ring:
          col_net: P6
          key:
            splay: -5
            stagger: 12
        middle:
          col_net: P7
          key.stagger: 5
        index:
          col_net: P8
          key.stagger: -6
        inner:
          col_net: P9
          key.stagger: -2
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [0, -19]
      columns:
        near:
        home.key:
          splay: -15
          origin: [-11.75, -9]
        far.key:
          splay: -15
          origin: [-9.5, -9]
      rows:
        thumb:
  rotate: 
  mirror: &mirror
    ref: matrix_pinky_home
    distance: 300

outlines:
  switches:
    - what: rectangle
      where: true
      asym: source
      size: 14
  keycaps:
    - what: rectangle 
      where: true
      asym: source
      size: [cx, cy] 
      corner: 1
  case_left:
    - what: polygon
      points:
        - ref: matrix_outer_nums
          shift: [left,  up] #tl
        - ref: matrix_ring_nums
          shift: [left,  up] #tl
        - ref: matrix_middle_nums
          shift: [left,  up] #tl
        - ref: matrix_middle_nums
          shift: [right,  up] #tr
        - ref: matrix_index_nums
          shift: [right,  up] #tr
        - ref: matrix_inner_nums
          shift: [right,  up] #tr
        - ref: matrix_inner_nums
          shift: [ 3.0 cx + off,  up]
        - ref: thumbfan_far_thumb
          shift: [right,  up] #tr
        - ref: thumbfan_far_thumb
          shift: [right, down] #br
        - ref: thumbfan_far_thumb
          shift: [left, down] #bl
        - ref: thumbfan_home_thumb
          shift: [left, down] #bl
        - ref: thumbfan_near_thumb
          shift: [left, down] #bl
        - ref: matrix_index_bottom
          shift: [right-off, down] #bl
        - ref: matrix_ring_bottom
          shift: [left+2off, down] #bl
        - ref: matrix_pinky_bottom
          shift: [right, down] #bl
        - ref: matrix_outer_bottom
          shift: [left, down] #bl
  full_left:
    - name: case_left
    - operation: subtract
      name: keycaps
# cases:
# TODO: have not vetted below
pcbs.tablua:
  footprints:
    led:
      what: sk6812mini
      where: true
      adjust:
        shift: [0, -5]
      params:
        din: "{{led_in}}"
        dout: "{{led_out}}"
        cutout: true
    diode:
      what: sod-123w
      where: true
      params:
        from: "{{name}}"
        to: "{{row_net}}"
      adjust:
        shift: [ -7.6, -1.6 ]
        rotate: 90
    choc:
      what: choc
      where: true
      params:
        keycaps: true
        reverse: true
        hotswap: true
        from: "{{col_net}}"
        to: "{{name}}"
    promicro:
      what: promicro_pretty
      where:
        ref: main_inner_home
      adjust:
        shift: [22, 6.5]
        rotate: -90
#   pcb_left:
#     outlines:
#       - outline: case_left
#     footprints:
#       - where: true
#         asym: both
#         what: mx
#         params:
#           - hotswap: true
